import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import { NavBar } from '../NavBar';
import { Inter } from 'next/font/google';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

type props={
    children:React.ReactNode
}

export const MainLayout = ({children}:props) => {
  return (
    <>
        <Head>
            <title>Home-PrimeraApp</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <NavBar/>
            {children}
        </main>
    </>
  )
}
